name: flutter_dooly_creator
description: A Flutter Image Creator application.
authors:
  - JAICHANG.PARK <aristojeff@gmail.com>
homepage: "https://github.com/JAICHANGPARK"
repository: https://github.com/JAICHANGPARK/flutter_dooly_creator
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.2.4+12

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: any
  cupertino_icons: ^1.0.4
  transparent_image: ^2.0.0
  cached_network_image: ^3.2.0
#  flutter_neumorphic: ^3.1.0
  smooth_page_indicator: ^1.0.0+2
  path: any
  path_provider: any
  permission_handler: any
  image_gallery_saver: any
  intl: any
  firebase_core: ^1.14.1
  firebase_analytics: ^9.1.5
  fluttertoast: ^8.0.9
  esys_flutter_share_plus: any
  #  esys_flutter_share:
#    git:
#      url: https://github.com/trustmefelix/esys-flutter-share.git

  in_app_review: ^2.0.4
  in_app_update: ^3.0.0

  package_info: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
