name: flutter_dooly_creator
description: A Flutter Image Creator application.
authors:
  - JAICHANG.PARK <aristojeff@gmail.com>
homepage: "https://github.com/JAICHANGPARK"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.1.0+7

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  transparent_image: ^1.0.0
  cached_network_image: ^2.5.1
  flutter_neumorphic: ^3.1.0
  smooth_page_indicator: ^0.2.1
  path: any
  path_provider: any
  permission_handler: any
  image_gallery_saver: any
  intl: any
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  fluttertoast: ^7.1.8
  esys_flutter_share: ^1.0.2

  in_app_review: ^1.0.4
  in_app_update: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/icon/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
